FROM ubuntu:18.04
RUN yes | apt-get update && \
    yes | apt install nano && \
    yes | apt install vim && \
    apt-get install -y libedit-dev && \
    yes | apt install racket && \
    yes | apt install build-essential
