---
name : computer-science-201-fall-2019-lab-4
break: True
indent: 4
---

myimages/_data:
    Part1.rkt:
        ConfirmFileExists
        MatchFileFragment --fragment "(*(* 4/3 pi)(* r r r))" --count 1
        
    ex4.ps:
        ConfirmFileExists
    ex5.ps:
        ConfirmFileExists

ReflectionLab4.pdf:
    ConfirmFileExists
